export const MEGA = "#6befa3"
export const QUINA = "#8666ef"
export const LOTOF = "#dd7ac6"
export const LOTOM = "#ffab64"
export const TIME = "#5aad7d"
export const DIA = "#bfaf83"
export const RESULT = "#efefef"